get http://localhost:3344

###
post http://localhost:3344/addUser

###
post http://localhost:3344/echoPost
Content-Type: application/x-www-form-urlencoded

campo1=v1&fecha=14/4/424

###
post http://localhost:3344/echoPostJson
Content-Type: application/json

{"cmpo":"1"}

###
post http://localhost:3344/echoPost?a=1&a=2&a=3
Content-Type: application/x-www-form-urlencoded

a=1&a=2&a=3&person[name]=jose&person[age]=45

###
post http://localhost:3344/echoParamPost/222/facturas/555
Content-Type: application/x-www-form-urlencoded

a=1&a=2&a=3&person[name]=jose&person[age]=45

###
get http://localhost:3344/p1.html

###
post http://localhost:3344/minio/createBucket
Content-Type: application/json

{"nombre":"curso"}

###
delete http://localhost:3344/minio/curso/42-EXPRESS-POST-BODY.pdf